frontend/infrastructure/.gitignore, frontend/infrastructure/aws_amplify.tf, frontend/infrastructure/main.tf, frontend/infrastructure/provider.tf, frontend/infrastructure/readme.txt, frontend/infrastructure/variables.tf, frontend/package.json
This PR: 
- Add Terraform to create AWS Amplify Resources
- Update homepage URL in React config
=> Deploy React App on Amplify

frontend/src/App.js
Modified the reader at the bottom of the simple website to call `api.squeak.today`. Would make the `cognito-authentication-simple` branch basically be an overall MVP basic features branch
=> Simple reader changes into simple cognito branch

backend/go.mod, backend/go.sum, backend/main.go, backend/notes.md, frontend/package-lock.json, frontend/package.json, frontend/src/Account.js, frontend/src/App.js, frontend/src/Status.js, frontend/src/UserPool.js, infrastructure/.gitignore, infrastructure/main.tf, infrastructure/readme.md, infrastructure/readme.txt
Current main is useless + should be deprecated `feat/cognito-authentication-simple` isn't ready either but at least will have a base to work on.
=> Cognito Accounts + Simple Story Reader

frontend/src/App.js, frontend/src/context/ContextStyles.js, frontend/src/context/NotificationContext.js, frontend/src/pages/Learn.js
Add a little notification red and green at the top of the website, callable as a context.
=> feat: Error and Success Notifications

frontend/src/components/StoryBrowser.js, frontend/src/pages/Learn.js
- adds correct languages and topics to drop down
- adds news vs story dropdown for browser filter
- fixes issue of only 10 content showing by using pagination
=> bug: pagination query in browser

frontend/src/components/StoryReader.js, frontend/src/lib/lang_codes.js, frontend/src/pages/Learn.js
=> fix: #32 by piping in lang code constants

frontend/src/components/StoryBrowser.js
=> feat: Add AI disclaimer

frontend/src/components/BasicPage.js, frontend/src/components/StoryBrowser.js, frontend/src/components/StoryList.js, frontend/src/components/StyledComponents.js, frontend/src/pages/Home.js
- Filters are now a 2x2 grid on mobile
- Header Logo goes away in mobile to make the size of the header reasonable (mouse stays)
- There's more, but they were minor but cleaned it up
=> changed css to make it more responsive on mobile

frontend/public/contact-support.html, frontend/src/components/BasicPage.js, frontend/src/pages/Auth.js, frontend/src/styles/AuthPageStyles.js
matches our design better and more customization options. login with google on https://tally.so
=> Feat: support/feedback form on tally

frontend/src/components/StoryBrowser.js
changes dropdown for CEFR difficulty level to use more common terms
=> chore: understandable cefr labels

frontend/src/components/StoryBlock.js, frontend/src/components/StoryList.js
adds date tags to the story browser bocks
=> feat: Add date tags

frontend/src/components/StyledComponents.js, frontend/src/pages/Home.js, frontend/src/styles/AuthPageStyles.js
issue #79 
- changed css for button in the header
- forced image aspect ratio to be 1:1
=> added aspect ratio change and header button fix

README.md, api/gemini/gemini.go, api/main.go, api/prompts/prompts.go, frontend/public/index.html, frontend/src/App.js, frontend/src/components/BasicPage.js, frontend/src/components/LoadingSpinner.js, frontend/src/components/SidePanel.js, frontend/src/components/StoryReader.js, frontend/src/components/StyledComponents.js, frontend/src/pages/Learn.js, frontend/src/pages/Read.js, frontend/src/styles/ReadPageStyles.js, infrastructure/gateway.tf, infrastructure/outputs.tf, queue_filler/main.go
A full launch branch. Adds a major feature (content questions) and makes the reader a separate page.
- it is functional, the tooltip has been added back. it has not removed any features, only added new ones so it is technically reader.
- we can do #52 and thus simultaneously solve #56 
- though this release is a good time to do sentence translation @pranavbedi
=> feat: Reader page with side panel and questions for learning content

frontend/src/pages/Read.js
=> bug: tooltip goes away on scroll #87

README.md, api/gemini/gemini.go, api/main.go, api/prompts/prompts.go, frontend/src/components/SidePanel.js, frontend/src/pages/Read.js, frontend/src/styles/ReadPageStyles.js, infrastructure/WORKSPACES.md
Adds explanations for question fails and suggestions for passes.
=> feat: QNA explanations

README.md, frontend/src/components/ProfileDashboard.js, frontend/src/components/StoryBrowser.js, frontend/src/components/Tutorial/Screen5.js, frontend/src/lib/topics.js, queue_filler/main.go, supabase/migrations/007_questions_cascade.sql
https://github.com/squeak-today/squeak/issues/121
Adds new topics. Makes organization of adding topics easier.
=> feat: new topics

supabase/migrations/001_create.sql, supabase/migrations/002_date_uniqueness.sql, supabase/migrations/004_user_profiles.sql, supabase/migrations/005_daily_progress.sql
misnamed branch sorry
makes migrations idempotent to make migrations onto the production branch work
=> tool: idempotent migrations

infrastructure/gateway.tf
=> tool: logs for api gateway

frontend/src/pages/TeacherDashboard.js
@connortbot @pranavbedi pls review
=> temp bug fix prior to demo

API.md, api/audio/audio.go, api/docs/docs.go, api/docs/openapi3.yaml, api/docs/swagger.json, api/docs/swagger.yaml, api/go.mod, api/go.sum, api/handlers/audiohandler/audio.go, api/handlers/stripehandler/stripe.go, api/main.go, api/models/audio.go, api/models/stripe.go, frontend/infrastructure/aws_amplify.tf, frontend/infrastructure/provider.tf, frontend/src/components/LoadingSpinner.js, frontend/src/components/RecordButton.tsx, frontend/src/components/SidePanel.js, frontend/src/hooks/useAudioAPI.ts, frontend/src/hooks/useAuthenticatedAPI.ts, frontend/src/lib/clients/types.ts, frontend/src/lib/lang_codes.ts, frontend/src/styles/ReadPageStyles.js, frontend/src/styles/components/RecordButtonStyles.ts, infrastructure/gateway.tf, infrastructure/lambda_front.tf, infrastructure/variables.tf
Primitive setup for a webhook with no case handling,
=> feat: Basic Stripe Webhook Endpoint

API.md, api/audio/audio.go, api/docs/docs.go, api/docs/openapi3.yaml, api/docs/swagger.json, api/docs/swagger.yaml, api/handlers/audiohandler/audio.go, api/main.go, api/models/audio.go, frontend/src/components/LoadingSpinner.js, frontend/src/components/RecordButton.tsx, frontend/src/components/SidePanel.js, frontend/src/hooks/useAudioAPI.ts, frontend/src/hooks/useAuthenticatedAPI.ts, frontend/src/lib/clients/types.ts, frontend/src/lib/lang_codes.ts, frontend/src/styles/ReadPageStyles.js, frontend/src/styles/components/RecordButtonStyles.ts, infrastructure/gateway.tf
speak your answers.
uses google simple STT API, but maybe a better model in the future. Also does not stream the input.
=> feat: Spoken Answers

api/audio/eleven.go, api/docs/docs.go, api/docs/openapi3.yaml, api/docs/swagger.json, api/docs/swagger.yaml, api/handlers/billinghandler/billing.go, api/handlers/handler.go, api/handlers/orghandler/payments.go, api/models/error.go, api/supabase/organizations.go, api/supabase/usage.go, dashboard/src/components/settings/OrganizationSettings.tsx, dashboard/src/pages/Settings.tsx, frontend/src/components/NavPage.tsx, frontend/src/components/SidePanel.js, frontend/src/pages/Profile.tsx, infrastructure/gateway.tf
Introduces Classroom plan which gives premium access to all students. UI fixes.
=> feat: Teacher billing
